### ISSUE TITLE
@enpoint?

### ISSUE THREAD

**Issue by whitetigle** [senx/VSCode-WarpScriptLanguage#24]
Hi,
I'm trying to change  the endpoint like you indicated in your doc by adding OVH url at the start of my `.mc2` file 
`// @endpoint https://warp10.gra1.metrics.ovh.net/api/v0/exec`

However I get a `ECONNREFUSED 127.0.0.1:8080` error. So I guess I'm not doing this correctly.

Thanks for your help!

**Comment by whitetigle** [comment]
Hi, just tried again this mornning. FYI I'm now using the extension from a windows 10 machine and docker.
Changing enpoint to local docker machine ip does not work, I get the same error message `ECONNREFUSED 127.0.0.1:808`. Thanks for your help!

**Comment by whitetigle** [comment]
Ok changing configuration in vscode parameters does the trick. Maybe that's the way to do it?

**Comment by Giwi** [comment]
You can do both ways.

I usually use preferences, but my colleagues use the annotation. I just tried it, it works fine (against our distributed cluster and a local docker image). 

Are you sure about your local url (127.0.0.1:808) ? Isn't it listening on the 8080 port?

To my opinion, the request is sent to the right server, nevertheless, a standard Warp 10 instance do not return 'content-type' header on a exec response, while your Warp 10 instance (warp10.gra1.metrics.ovh.net) add `content-type: "application/json"`. We have a dummy test here : https://github.com/Giwi/VSCode-WarpScriptLangage/blob/master/src/features/execCommand.ts#L165 so, the response from your instance is never displayed. According to issue #24, it seems, you have a customized Warp 10 which do not behave like a standard one. 

It will be fixed in a future release.

**Comment by whitetigle** [comment]
Hi!

FYI, I'm using [latest warp docker image ](https://store.docker.com/community/images/warp10io/warp10/tags) on my local windows machine using 
`docker run --volume=/var/warp10:/data -p 8080:8080 -p 8081:8081 -d -i warp10io/warp10:latest`

> Are you sure about your local url (127.0.0.1:808) ? Isn't it listening on the 8080 port?

Sorry it was a typo. It was listening on 8080. But the local ip is 192.168.99.100 since according to the doc,

> using Docker on Mac OS or Windows, there is no binding between Warp 10 API address and the host (docker is runned throw a Virtual Machine). To reach Warp 10 you need to replace 127.0.0.1 by the real Ip address of the container.

I don't know if that gives you interesting information though...

**Comment by Giwi** [comment]
so do I

**Comment by whitetigle** [comment]
Anyway since I have found one way to change the endpoint, please feel free to close the issue.
Thanks for your answer and for the extension, It's been very useful so far! 👏

**Comment by Giwi** [comment]
thanks for your encouragements :) I will try it on Windows later (we have no Windows OS at work).

**Comment by Giwi** [comment]
Hi, it seems to be fixed on windows, could you give a try with the 1.0.0 version?
